# Generated by Django 6.0 on 2026-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_description_order_price_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
